// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlcgen

import (
	"context"
)

const countEvents = `-- name: CountEvents :one
SELECT count(*) FROM events
`

func (q *Queries) CountEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (kind, ip)
VALUES (?, ?)
RETURNING id, kind, ip, created_at
`

type CreateEventParams struct {
	Kind string `json:"kind"`
	Ip   string `json:"ip"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent, arg.Kind, arg.Ip)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Ip,
		&i.CreatedAt,
	)
	return i, err
}

const getRecentEvents = `-- name: GetRecentEvents :many
SELECT id, kind, ip, created_at FROM events
ORDER BY id DESC
LIMIT ?
`

func (q *Queries) GetRecentEvents(ctx context.Context, limit int64) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, getRecentEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Ip,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
