// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package sqlcgen

import (
	"context"
)

const countMessages = `-- name: CountMessages :one
SELECT count(*) FROM messages
`

func (q *Queries) CountMessages(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMessages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (author, body)
VALUES (?, ?)
RETURNING id, author, body, created_at
`

type CreateMessageParams struct {
	Author string `json:"author"`
	Body   string `json:"body"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage, arg.Author, arg.Body)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Author,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const getRecentMessages = `-- name: GetRecentMessages :many
SELECT id, author, body, created_at FROM messages
ORDER BY id DESC
LIMIT ?
`

func (q *Queries) GetRecentMessages(ctx context.Context, limit int64) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getRecentMessages, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Author,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
