// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

type Event struct {
	ID        int64  `json:"id"`
	Kind      string `json:"kind"`
	Ip        string `json:"ip"`
	CreatedAt int64  `json:"created_at"`
}
